################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (12.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
/home/lukasschoepf/Documents/ProjectWork_2/Projectwork2_Code/ST32N6AI/MatMul/MatMulN6/STM32N6/Application/NUCLEO-N657X0-Q/Src/app_fuseprogramming.c \
/home/lukasschoepf/Documents/ProjectWork_2/Projectwork2_Code/ST32N6AI/MatMul/MatMulN6/STM32N6/Application/NUCLEO-N657X0-Q/Src/crop_img.c \
/home/lukasschoepf/Documents/ProjectWork_2/Projectwork2_Code/ST32N6AI/MatMul/MatMulN6/STM32N6/Application/NUCLEO-N657X0-Q/Src/main.c \
/home/lukasschoepf/Documents/ProjectWork_2/Projectwork2_Code/ST32N6AI/MatMul/MatMulN6/STM32N6/Middlewares/AI_Runtime/Npu/Devices/STM32N6XX/mcu_cache.c \
/home/lukasschoepf/Documents/ProjectWork_2/Projectwork2_Code/ST32N6AI/MatMul/MatMulN6/STM32N6/Model/ownModels/simpleDense_quant/NetworkFiles/network.c \
/home/lukasschoepf/Documents/ProjectWork_2/Projectwork2_Code/ST32N6AI/MatMul/MatMulN6/STM32N6/Middlewares/AI_Runtime/Npu/Devices/STM32N6XX/npu_cache.c \
/home/lukasschoepf/Documents/ProjectWork_2/Projectwork2_Code/ST32N6AI/MatMul/MatMulN6/STM32N6/Application/NUCLEO-N657X0-Q/Src/stm32_lcd_ex.c \
/home/lukasschoepf/Documents/ProjectWork_2/Projectwork2_Code/ST32N6AI/MatMul/MatMulN6/STM32N6/Application/NUCLEO-N657X0-Q/Src/stm32n6xx_it.c \
/home/lukasschoepf/Documents/ProjectWork_2/Projectwork2_Code/ST32N6AI/MatMul/MatMulN6/STM32N6/Application/NUCLEO-N657X0-Q/Src/syscalls.c 

OBJS += \
./Application/app_fuseprogramming.o \
./Application/crop_img.o \
./Application/main.o \
./Application/mcu_cache.o \
./Application/network.o \
./Application/npu_cache.o \
./Application/stm32_lcd_ex.o \
./Application/stm32n6xx_it.o \
./Application/syscalls.o 

C_DEPS += \
./Application/app_fuseprogramming.d \
./Application/crop_img.d \
./Application/main.d \
./Application/mcu_cache.d \
./Application/network.d \
./Application/npu_cache.d \
./Application/stm32_lcd_ex.d \
./Application/stm32n6xx_it.d \
./Application/syscalls.d 


# Each subdirectory must supply rules for building sources it contributes
Application/app_fuseprogramming.o: /home/lukasschoepf/Documents/ProjectWork_2/Projectwork2_Code/ST32N6AI/MatMul/MatMulN6/STM32N6/Application/NUCLEO-N657X0-Q/Src/app_fuseprogramming.c Application/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DSTM32N6570_NUCLEO_REV -DSCR_LIB_USE_SPI -DSCR_LIB_USE_NONE -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DLL_ATON_DUMP_DEBUG_API -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -c -I../../Inc -I../../../../Middlewares/ai-postprocessing-wrapper -I../../../../Middlewares/lib_vision_models_pp/lib_vision_models_pp/Inc -I../../../../Middlewares/AI_Runtime/Npu/ll_aton -I../../../../Middlewares/AI_Runtime/Npu/Devices/STM32N6XX -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../../../STM32Cube_FW_N6/Drivers/BSP/STM32N6xx_Nucleo -I../../../../Middlewares/Camera_Middleware/ISP_Library/isp/Inc -I../../../../Middlewares/Camera_Middleware/ISP_Library/evision/Inc -I../../../../Middlewares/AI_Runtime/Inc -I../../../../STM32Cube_FW_N6/Utilities/lcd -I../../../../Middlewares/Camera_Middleware -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../../../Middlewares/Camera_Middleware/sensors -I../../../../Middlewares/Camera_Middleware/sensors/imx335 -I../../../../Middlewares/Camera_Middleware/sensors/vd6g -I../../../../Middlewares/Camera_Middleware/sensors/vd55g1 -I../../../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/core/inc -I../../../../STM32Cube_FW_N6/Middlewares/ST/usbx/ports/generic/inc -I../../../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/usbx_device_classes/inc -I../../../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/usbx_stm32_device_controllers -I../../../../Middlewares/screenl/Inc -I../../../../Middlewares/screenl/ili9341 -I../../../../Middlewares/screenl/uvcl/Inc -I../../../../Middlewares/screenl/uvcl/Src -I../../../../Middlewares/screenl/uvcl/Inc/usbx -I../../../../Middlewares/screenl/uvcl/Src/usbx -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/crop_img.o: /home/lukasschoepf/Documents/ProjectWork_2/Projectwork2_Code/ST32N6AI/MatMul/MatMulN6/STM32N6/Application/NUCLEO-N657X0-Q/Src/crop_img.c Application/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DSTM32N6570_NUCLEO_REV -DSCR_LIB_USE_SPI -DSCR_LIB_USE_NONE -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DLL_ATON_DUMP_DEBUG_API -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -c -I../../Inc -I../../../../Middlewares/ai-postprocessing-wrapper -I../../../../Middlewares/lib_vision_models_pp/lib_vision_models_pp/Inc -I../../../../Middlewares/AI_Runtime/Npu/ll_aton -I../../../../Middlewares/AI_Runtime/Npu/Devices/STM32N6XX -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../../../STM32Cube_FW_N6/Drivers/BSP/STM32N6xx_Nucleo -I../../../../Middlewares/Camera_Middleware/ISP_Library/isp/Inc -I../../../../Middlewares/Camera_Middleware/ISP_Library/evision/Inc -I../../../../Middlewares/AI_Runtime/Inc -I../../../../STM32Cube_FW_N6/Utilities/lcd -I../../../../Middlewares/Camera_Middleware -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../../../Middlewares/Camera_Middleware/sensors -I../../../../Middlewares/Camera_Middleware/sensors/imx335 -I../../../../Middlewares/Camera_Middleware/sensors/vd6g -I../../../../Middlewares/Camera_Middleware/sensors/vd55g1 -I../../../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/core/inc -I../../../../STM32Cube_FW_N6/Middlewares/ST/usbx/ports/generic/inc -I../../../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/usbx_device_classes/inc -I../../../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/usbx_stm32_device_controllers -I../../../../Middlewares/screenl/Inc -I../../../../Middlewares/screenl/ili9341 -I../../../../Middlewares/screenl/uvcl/Inc -I../../../../Middlewares/screenl/uvcl/Src -I../../../../Middlewares/screenl/uvcl/Inc/usbx -I../../../../Middlewares/screenl/uvcl/Src/usbx -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/main.o: /home/lukasschoepf/Documents/ProjectWork_2/Projectwork2_Code/ST32N6AI/MatMul/MatMulN6/STM32N6/Application/NUCLEO-N657X0-Q/Src/main.c Application/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DSTM32N6570_NUCLEO_REV -DSCR_LIB_USE_SPI -DSCR_LIB_USE_NONE -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DLL_ATON_DUMP_DEBUG_API -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -c -I../../Inc -I../../../../Middlewares/ai-postprocessing-wrapper -I../../../../Middlewares/lib_vision_models_pp/lib_vision_models_pp/Inc -I../../../../Middlewares/AI_Runtime/Npu/ll_aton -I../../../../Middlewares/AI_Runtime/Npu/Devices/STM32N6XX -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../../../STM32Cube_FW_N6/Drivers/BSP/STM32N6xx_Nucleo -I../../../../Middlewares/Camera_Middleware/ISP_Library/isp/Inc -I../../../../Middlewares/Camera_Middleware/ISP_Library/evision/Inc -I../../../../Middlewares/AI_Runtime/Inc -I../../../../STM32Cube_FW_N6/Utilities/lcd -I../../../../Middlewares/Camera_Middleware -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../../../Middlewares/Camera_Middleware/sensors -I../../../../Middlewares/Camera_Middleware/sensors/imx335 -I../../../../Middlewares/Camera_Middleware/sensors/vd6g -I../../../../Middlewares/Camera_Middleware/sensors/vd55g1 -I../../../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/core/inc -I../../../../STM32Cube_FW_N6/Middlewares/ST/usbx/ports/generic/inc -I../../../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/usbx_device_classes/inc -I../../../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/usbx_stm32_device_controllers -I../../../../Middlewares/screenl/Inc -I../../../../Middlewares/screenl/ili9341 -I../../../../Middlewares/screenl/uvcl/Inc -I../../../../Middlewares/screenl/uvcl/Src -I../../../../Middlewares/screenl/uvcl/Inc/usbx -I../../../../Middlewares/screenl/uvcl/Src/usbx -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/mcu_cache.o: /home/lukasschoepf/Documents/ProjectWork_2/Projectwork2_Code/ST32N6AI/MatMul/MatMulN6/STM32N6/Middlewares/AI_Runtime/Npu/Devices/STM32N6XX/mcu_cache.c Application/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DSTM32N6570_NUCLEO_REV -DSCR_LIB_USE_SPI -DSCR_LIB_USE_NONE -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DLL_ATON_DUMP_DEBUG_API -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -c -I../../Inc -I../../../../Middlewares/ai-postprocessing-wrapper -I../../../../Middlewares/lib_vision_models_pp/lib_vision_models_pp/Inc -I../../../../Middlewares/AI_Runtime/Npu/ll_aton -I../../../../Middlewares/AI_Runtime/Npu/Devices/STM32N6XX -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../../../STM32Cube_FW_N6/Drivers/BSP/STM32N6xx_Nucleo -I../../../../Middlewares/Camera_Middleware/ISP_Library/isp/Inc -I../../../../Middlewares/Camera_Middleware/ISP_Library/evision/Inc -I../../../../Middlewares/AI_Runtime/Inc -I../../../../STM32Cube_FW_N6/Utilities/lcd -I../../../../Middlewares/Camera_Middleware -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../../../Middlewares/Camera_Middleware/sensors -I../../../../Middlewares/Camera_Middleware/sensors/imx335 -I../../../../Middlewares/Camera_Middleware/sensors/vd6g -I../../../../Middlewares/Camera_Middleware/sensors/vd55g1 -I../../../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/core/inc -I../../../../STM32Cube_FW_N6/Middlewares/ST/usbx/ports/generic/inc -I../../../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/usbx_device_classes/inc -I../../../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/usbx_stm32_device_controllers -I../../../../Middlewares/screenl/Inc -I../../../../Middlewares/screenl/ili9341 -I../../../../Middlewares/screenl/uvcl/Inc -I../../../../Middlewares/screenl/uvcl/Src -I../../../../Middlewares/screenl/uvcl/Inc/usbx -I../../../../Middlewares/screenl/uvcl/Src/usbx -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/network.o: /home/lukasschoepf/Documents/ProjectWork_2/Projectwork2_Code/ST32N6AI/MatMul/MatMulN6/STM32N6/Model/ownModels/simpleDense_quant/NetworkFiles/network.c Application/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DSTM32N6570_NUCLEO_REV -DSCR_LIB_USE_SPI -DSCR_LIB_USE_NONE -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DLL_ATON_DUMP_DEBUG_API -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -c -I../../Inc -I../../../../Middlewares/ai-postprocessing-wrapper -I../../../../Middlewares/lib_vision_models_pp/lib_vision_models_pp/Inc -I../../../../Middlewares/AI_Runtime/Npu/ll_aton -I../../../../Middlewares/AI_Runtime/Npu/Devices/STM32N6XX -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../../../STM32Cube_FW_N6/Drivers/BSP/STM32N6xx_Nucleo -I../../../../Middlewares/Camera_Middleware/ISP_Library/isp/Inc -I../../../../Middlewares/Camera_Middleware/ISP_Library/evision/Inc -I../../../../Middlewares/AI_Runtime/Inc -I../../../../STM32Cube_FW_N6/Utilities/lcd -I../../../../Middlewares/Camera_Middleware -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../../../Middlewares/Camera_Middleware/sensors -I../../../../Middlewares/Camera_Middleware/sensors/imx335 -I../../../../Middlewares/Camera_Middleware/sensors/vd6g -I../../../../Middlewares/Camera_Middleware/sensors/vd55g1 -I../../../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/core/inc -I../../../../STM32Cube_FW_N6/Middlewares/ST/usbx/ports/generic/inc -I../../../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/usbx_device_classes/inc -I../../../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/usbx_stm32_device_controllers -I../../../../Middlewares/screenl/Inc -I../../../../Middlewares/screenl/ili9341 -I../../../../Middlewares/screenl/uvcl/Inc -I../../../../Middlewares/screenl/uvcl/Src -I../../../../Middlewares/screenl/uvcl/Inc/usbx -I../../../../Middlewares/screenl/uvcl/Src/usbx -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/npu_cache.o: /home/lukasschoepf/Documents/ProjectWork_2/Projectwork2_Code/ST32N6AI/MatMul/MatMulN6/STM32N6/Middlewares/AI_Runtime/Npu/Devices/STM32N6XX/npu_cache.c Application/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DSTM32N6570_NUCLEO_REV -DSCR_LIB_USE_SPI -DSCR_LIB_USE_NONE -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DLL_ATON_DUMP_DEBUG_API -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -c -I../../Inc -I../../../../Middlewares/ai-postprocessing-wrapper -I../../../../Middlewares/lib_vision_models_pp/lib_vision_models_pp/Inc -I../../../../Middlewares/AI_Runtime/Npu/ll_aton -I../../../../Middlewares/AI_Runtime/Npu/Devices/STM32N6XX -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../../../STM32Cube_FW_N6/Drivers/BSP/STM32N6xx_Nucleo -I../../../../Middlewares/Camera_Middleware/ISP_Library/isp/Inc -I../../../../Middlewares/Camera_Middleware/ISP_Library/evision/Inc -I../../../../Middlewares/AI_Runtime/Inc -I../../../../STM32Cube_FW_N6/Utilities/lcd -I../../../../Middlewares/Camera_Middleware -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../../../Middlewares/Camera_Middleware/sensors -I../../../../Middlewares/Camera_Middleware/sensors/imx335 -I../../../../Middlewares/Camera_Middleware/sensors/vd6g -I../../../../Middlewares/Camera_Middleware/sensors/vd55g1 -I../../../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/core/inc -I../../../../STM32Cube_FW_N6/Middlewares/ST/usbx/ports/generic/inc -I../../../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/usbx_device_classes/inc -I../../../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/usbx_stm32_device_controllers -I../../../../Middlewares/screenl/Inc -I../../../../Middlewares/screenl/ili9341 -I../../../../Middlewares/screenl/uvcl/Inc -I../../../../Middlewares/screenl/uvcl/Src -I../../../../Middlewares/screenl/uvcl/Inc/usbx -I../../../../Middlewares/screenl/uvcl/Src/usbx -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/stm32_lcd_ex.o: /home/lukasschoepf/Documents/ProjectWork_2/Projectwork2_Code/ST32N6AI/MatMul/MatMulN6/STM32N6/Application/NUCLEO-N657X0-Q/Src/stm32_lcd_ex.c Application/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DSTM32N6570_NUCLEO_REV -DSCR_LIB_USE_SPI -DSCR_LIB_USE_NONE -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DLL_ATON_DUMP_DEBUG_API -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -c -I../../Inc -I../../../../Middlewares/ai-postprocessing-wrapper -I../../../../Middlewares/lib_vision_models_pp/lib_vision_models_pp/Inc -I../../../../Middlewares/AI_Runtime/Npu/ll_aton -I../../../../Middlewares/AI_Runtime/Npu/Devices/STM32N6XX -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../../../STM32Cube_FW_N6/Drivers/BSP/STM32N6xx_Nucleo -I../../../../Middlewares/Camera_Middleware/ISP_Library/isp/Inc -I../../../../Middlewares/Camera_Middleware/ISP_Library/evision/Inc -I../../../../Middlewares/AI_Runtime/Inc -I../../../../STM32Cube_FW_N6/Utilities/lcd -I../../../../Middlewares/Camera_Middleware -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../../../Middlewares/Camera_Middleware/sensors -I../../../../Middlewares/Camera_Middleware/sensors/imx335 -I../../../../Middlewares/Camera_Middleware/sensors/vd6g -I../../../../Middlewares/Camera_Middleware/sensors/vd55g1 -I../../../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/core/inc -I../../../../STM32Cube_FW_N6/Middlewares/ST/usbx/ports/generic/inc -I../../../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/usbx_device_classes/inc -I../../../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/usbx_stm32_device_controllers -I../../../../Middlewares/screenl/Inc -I../../../../Middlewares/screenl/ili9341 -I../../../../Middlewares/screenl/uvcl/Inc -I../../../../Middlewares/screenl/uvcl/Src -I../../../../Middlewares/screenl/uvcl/Inc/usbx -I../../../../Middlewares/screenl/uvcl/Src/usbx -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/stm32n6xx_it.o: /home/lukasschoepf/Documents/ProjectWork_2/Projectwork2_Code/ST32N6AI/MatMul/MatMulN6/STM32N6/Application/NUCLEO-N657X0-Q/Src/stm32n6xx_it.c Application/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DSTM32N6570_NUCLEO_REV -DSCR_LIB_USE_SPI -DSCR_LIB_USE_NONE -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DLL_ATON_DUMP_DEBUG_API -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -c -I../../Inc -I../../../../Middlewares/ai-postprocessing-wrapper -I../../../../Middlewares/lib_vision_models_pp/lib_vision_models_pp/Inc -I../../../../Middlewares/AI_Runtime/Npu/ll_aton -I../../../../Middlewares/AI_Runtime/Npu/Devices/STM32N6XX -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../../../STM32Cube_FW_N6/Drivers/BSP/STM32N6xx_Nucleo -I../../../../Middlewares/Camera_Middleware/ISP_Library/isp/Inc -I../../../../Middlewares/Camera_Middleware/ISP_Library/evision/Inc -I../../../../Middlewares/AI_Runtime/Inc -I../../../../STM32Cube_FW_N6/Utilities/lcd -I../../../../Middlewares/Camera_Middleware -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../../../Middlewares/Camera_Middleware/sensors -I../../../../Middlewares/Camera_Middleware/sensors/imx335 -I../../../../Middlewares/Camera_Middleware/sensors/vd6g -I../../../../Middlewares/Camera_Middleware/sensors/vd55g1 -I../../../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/core/inc -I../../../../STM32Cube_FW_N6/Middlewares/ST/usbx/ports/generic/inc -I../../../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/usbx_device_classes/inc -I../../../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/usbx_stm32_device_controllers -I../../../../Middlewares/screenl/Inc -I../../../../Middlewares/screenl/ili9341 -I../../../../Middlewares/screenl/uvcl/Inc -I../../../../Middlewares/screenl/uvcl/Src -I../../../../Middlewares/screenl/uvcl/Inc/usbx -I../../../../Middlewares/screenl/uvcl/Src/usbx -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/syscalls.o: /home/lukasschoepf/Documents/ProjectWork_2/Projectwork2_Code/ST32N6AI/MatMul/MatMulN6/STM32N6/Application/NUCLEO-N657X0-Q/Src/syscalls.c Application/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DSTM32N6570_NUCLEO_REV -DSCR_LIB_USE_SPI -DSCR_LIB_USE_NONE -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DLL_ATON_DUMP_DEBUG_API -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -c -I../../Inc -I../../../../Middlewares/ai-postprocessing-wrapper -I../../../../Middlewares/lib_vision_models_pp/lib_vision_models_pp/Inc -I../../../../Middlewares/AI_Runtime/Npu/ll_aton -I../../../../Middlewares/AI_Runtime/Npu/Devices/STM32N6XX -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../../../STM32Cube_FW_N6/Drivers/BSP/STM32N6xx_Nucleo -I../../../../Middlewares/Camera_Middleware/ISP_Library/isp/Inc -I../../../../Middlewares/Camera_Middleware/ISP_Library/evision/Inc -I../../../../Middlewares/AI_Runtime/Inc -I../../../../STM32Cube_FW_N6/Utilities/lcd -I../../../../Middlewares/Camera_Middleware -I../../../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../../../Middlewares/Camera_Middleware/sensors -I../../../../Middlewares/Camera_Middleware/sensors/imx335 -I../../../../Middlewares/Camera_Middleware/sensors/vd6g -I../../../../Middlewares/Camera_Middleware/sensors/vd55g1 -I../../../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/core/inc -I../../../../STM32Cube_FW_N6/Middlewares/ST/usbx/ports/generic/inc -I../../../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/usbx_device_classes/inc -I../../../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/usbx_stm32_device_controllers -I../../../../Middlewares/screenl/Inc -I../../../../Middlewares/screenl/ili9341 -I../../../../Middlewares/screenl/uvcl/Inc -I../../../../Middlewares/screenl/uvcl/Src -I../../../../Middlewares/screenl/uvcl/Inc/usbx -I../../../../Middlewares/screenl/uvcl/Src/usbx -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Application

clean-Application:
	-$(RM) ./Application/app_fuseprogramming.cyclo ./Application/app_fuseprogramming.d ./Application/app_fuseprogramming.o ./Application/app_fuseprogramming.su ./Application/crop_img.cyclo ./Application/crop_img.d ./Application/crop_img.o ./Application/crop_img.su ./Application/main.cyclo ./Application/main.d ./Application/main.o ./Application/main.su ./Application/mcu_cache.cyclo ./Application/mcu_cache.d ./Application/mcu_cache.o ./Application/mcu_cache.su ./Application/network.cyclo ./Application/network.d ./Application/network.o ./Application/network.su ./Application/npu_cache.cyclo ./Application/npu_cache.d ./Application/npu_cache.o ./Application/npu_cache.su ./Application/stm32_lcd_ex.cyclo ./Application/stm32_lcd_ex.d ./Application/stm32_lcd_ex.o ./Application/stm32_lcd_ex.su ./Application/stm32n6xx_it.cyclo ./Application/stm32n6xx_it.d ./Application/stm32n6xx_it.o ./Application/stm32n6xx_it.su ./Application/syscalls.cyclo ./Application/syscalls.d ./Application/syscalls.o ./Application/syscalls.su

.PHONY: clean-Application

