/**
  ******************************************************************************
  * @file    network_ecblobs.h
  * @brief   NN Code autogenerated DO NOT MODIFY IT
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2024 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  ******************************************************************************
  */


#ifdef __cplusplus
extern "C" {
#endif

#include "ll_aton_caches_interface.h"

#include <string.h>

#if !defined(ECBLOB_CONST_SECTION)
#define ECBLOB_CONST_SECTION /* Empty */
#endif
#if !defined(ECBLOB_RUNTIME_SECTION)
#define ECBLOB_RUNTIME_SECTION /* Empty */
#endif

ECBLOB_CONST_SECTION
static const uint64_t _ec_blob_1 [] =
{
  0x00000002ca057a7aUL, 0x0000000c0000003dUL
};


ECBLOB_CONST_SECTION
static const uint64_t _ec_blob_3 [] =
{
  0x00000003ca057a7aUL, 0x0000009d0000007dUL, 0x000000000000000cUL
};


// this function MUST be called ONLY ONCE once for initializing the network
bool LL_ATON_EC_Network_Init_Default(void)
{


  return true;
}

// this function should be called before each inference
bool LL_ATON_EC_Inference_Init_Default(void)
{


  return true;
}

#ifdef __cplusplus
}
#endif
