################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (12.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
/home/lukasschoepf/Documents/ProjectWork_2/Projectwork2_Code/ST32N6AI/ModelZooService/STM32N6/STM32Cube_FW_N6/Drivers/BSP/STM32N6570-DK/stm32n6570_discovery.c \
/home/lukasschoepf/Documents/ProjectWork_2/Projectwork2_Code/ST32N6AI/ModelZooService/STM32N6/STM32Cube_FW_N6/Drivers/BSP/STM32N6570-DK/stm32n6570_discovery_bus.c \
/home/lukasschoepf/Documents/ProjectWork_2/Projectwork2_Code/ST32N6AI/ModelZooService/STM32N6/STM32Cube_FW_N6/Drivers/BSP/STM32N6570-DK/stm32n6570_discovery_lcd.c \
/home/lukasschoepf/Documents/ProjectWork_2/Projectwork2_Code/ST32N6AI/ModelZooService/STM32N6/STM32Cube_FW_N6/Drivers/BSP/STM32N6570-DK/stm32n6570_discovery_xspi.c 

OBJS += \
./Drivers/BSP/STM32N6570-DK/stm32n6570_discovery.o \
./Drivers/BSP/STM32N6570-DK/stm32n6570_discovery_bus.o \
./Drivers/BSP/STM32N6570-DK/stm32n6570_discovery_lcd.o \
./Drivers/BSP/STM32N6570-DK/stm32n6570_discovery_xspi.o 

C_DEPS += \
./Drivers/BSP/STM32N6570-DK/stm32n6570_discovery.d \
./Drivers/BSP/STM32N6570-DK/stm32n6570_discovery_bus.d \
./Drivers/BSP/STM32N6570-DK/stm32n6570_discovery_lcd.d \
./Drivers/BSP/STM32N6570-DK/stm32n6570_discovery_xspi.d 


# Each subdirectory must supply rules for building sources it contributes
Drivers/BSP/STM32N6570-DK/stm32n6570_discovery.o: /home/lukasschoepf/Documents/ProjectWork_2/Projectwork2_Code/ST32N6AI/ModelZooService/STM32N6/STM32Cube_FW_N6/Drivers/BSP/STM32N6570-DK/stm32n6570_discovery.c Drivers/BSP/STM32N6570-DK/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DLL_ATON_DUMP_DEBUG_API -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -c -I../../Inc -I../../Middlewares/AI_Runtime/Npu/ll_aton -I../../Middlewares/AI_Runtime/Npu/Devices/STM32N6XX -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../STM32Cube_FW_N6/Drivers/BSP/STM32N6570-DK -I../../Middlewares/Camera_Middleware/ISP_Library/isp/Inc -I../../Middlewares/Camera_Middleware/ISP_Library/evision/Inc -I../../Middlewares/AI_Runtime/Inc -I../../STM32Cube_FW_N6/Utilities/lcd -I../../Middlewares/Camera_Middleware -I../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../Middlewares/Camera_Middleware/sensors -I../../Middlewares/Camera_Middleware/sensors/imx335 -I../../Middlewares/Camera_Middleware/sensors/vd6g -I../../Middlewares/Camera_Middleware/sensors/vd55g1 -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/STM32N6570-DK/stm32n6570_discovery_bus.o: /home/lukasschoepf/Documents/ProjectWork_2/Projectwork2_Code/ST32N6AI/ModelZooService/STM32N6/STM32Cube_FW_N6/Drivers/BSP/STM32N6570-DK/stm32n6570_discovery_bus.c Drivers/BSP/STM32N6570-DK/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DLL_ATON_DUMP_DEBUG_API -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -c -I../../Inc -I../../Middlewares/AI_Runtime/Npu/ll_aton -I../../Middlewares/AI_Runtime/Npu/Devices/STM32N6XX -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../STM32Cube_FW_N6/Drivers/BSP/STM32N6570-DK -I../../Middlewares/Camera_Middleware/ISP_Library/isp/Inc -I../../Middlewares/Camera_Middleware/ISP_Library/evision/Inc -I../../Middlewares/AI_Runtime/Inc -I../../STM32Cube_FW_N6/Utilities/lcd -I../../Middlewares/Camera_Middleware -I../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../Middlewares/Camera_Middleware/sensors -I../../Middlewares/Camera_Middleware/sensors/imx335 -I../../Middlewares/Camera_Middleware/sensors/vd6g -I../../Middlewares/Camera_Middleware/sensors/vd55g1 -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/STM32N6570-DK/stm32n6570_discovery_lcd.o: /home/lukasschoepf/Documents/ProjectWork_2/Projectwork2_Code/ST32N6AI/ModelZooService/STM32N6/STM32Cube_FW_N6/Drivers/BSP/STM32N6570-DK/stm32n6570_discovery_lcd.c Drivers/BSP/STM32N6570-DK/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DLL_ATON_DUMP_DEBUG_API -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -c -I../../Inc -I../../Middlewares/AI_Runtime/Npu/ll_aton -I../../Middlewares/AI_Runtime/Npu/Devices/STM32N6XX -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../STM32Cube_FW_N6/Drivers/BSP/STM32N6570-DK -I../../Middlewares/Camera_Middleware/ISP_Library/isp/Inc -I../../Middlewares/Camera_Middleware/ISP_Library/evision/Inc -I../../Middlewares/AI_Runtime/Inc -I../../STM32Cube_FW_N6/Utilities/lcd -I../../Middlewares/Camera_Middleware -I../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../Middlewares/Camera_Middleware/sensors -I../../Middlewares/Camera_Middleware/sensors/imx335 -I../../Middlewares/Camera_Middleware/sensors/vd6g -I../../Middlewares/Camera_Middleware/sensors/vd55g1 -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/BSP/STM32N6570-DK/stm32n6570_discovery_xspi.o: /home/lukasschoepf/Documents/ProjectWork_2/Projectwork2_Code/ST32N6AI/ModelZooService/STM32N6/STM32Cube_FW_N6/Drivers/BSP/STM32N6570-DK/stm32n6570_discovery_xspi.c Drivers/BSP/STM32N6570-DK/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DLL_ATON_DUMP_DEBUG_API -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_BARE_METAL -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -c -I../../Inc -I../../Middlewares/AI_Runtime/Npu/ll_aton -I../../Middlewares/AI_Runtime/Npu/Devices/STM32N6XX -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../STM32Cube_FW_N6/Drivers/BSP/STM32N6570-DK -I../../Middlewares/Camera_Middleware/ISP_Library/isp/Inc -I../../Middlewares/Camera_Middleware/ISP_Library/evision/Inc -I../../Middlewares/AI_Runtime/Inc -I../../STM32Cube_FW_N6/Utilities/lcd -I../../Middlewares/Camera_Middleware -I../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../Middlewares/Camera_Middleware/sensors -I../../Middlewares/Camera_Middleware/sensors/imx335 -I../../Middlewares/Camera_Middleware/sensors/vd6g -I../../Middlewares/Camera_Middleware/sensors/vd55g1 -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Drivers-2f-BSP-2f-STM32N6570-2d-DK

clean-Drivers-2f-BSP-2f-STM32N6570-2d-DK:
	-$(RM) ./Drivers/BSP/STM32N6570-DK/stm32n6570_discovery.cyclo ./Drivers/BSP/STM32N6570-DK/stm32n6570_discovery.d ./Drivers/BSP/STM32N6570-DK/stm32n6570_discovery.o ./Drivers/BSP/STM32N6570-DK/stm32n6570_discovery.su ./Drivers/BSP/STM32N6570-DK/stm32n6570_discovery_bus.cyclo ./Drivers/BSP/STM32N6570-DK/stm32n6570_discovery_bus.d ./Drivers/BSP/STM32N6570-DK/stm32n6570_discovery_bus.o ./Drivers/BSP/STM32N6570-DK/stm32n6570_discovery_bus.su ./Drivers/BSP/STM32N6570-DK/stm32n6570_discovery_lcd.cyclo ./Drivers/BSP/STM32N6570-DK/stm32n6570_discovery_lcd.d ./Drivers/BSP/STM32N6570-DK/stm32n6570_discovery_lcd.o ./Drivers/BSP/STM32N6570-DK/stm32n6570_discovery_lcd.su ./Drivers/BSP/STM32N6570-DK/stm32n6570_discovery_xspi.cyclo ./Drivers/BSP/STM32N6570-DK/stm32n6570_discovery_xspi.d ./Drivers/BSP/STM32N6570-DK/stm32n6570_discovery_xspi.o ./Drivers/BSP/STM32N6570-DK/stm32n6570_discovery_xspi.su

.PHONY: clean-Drivers-2f-BSP-2f-STM32N6570-2d-DK

